-- MySQL Script generated by MySQL Workbench
-- Fri Jul 21 03:52:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema comercio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `comercio` ;

-- -----------------------------------------------------
-- Schema comercio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comercio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `comercio` ;

-- -----------------------------------------------------
-- Table `comercio`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercio`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `f_last_name` VARCHAR(50) NOT NULL,
  `m_last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comercio`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercio`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `comercio`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `comercio`;
INSERT INTO `comercio`.`users` (`id`, `name`, `f_last_name`, `m_last_name`, `email`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES (1, 'Samuel', DEFAULT, DEFAULT, 'samuel@gmail.com', '$2y$10$K27jDZK5vzhpACqW.AC/a.8Q87dt7x8oJRwJMxaqjzhKEbcaCAWPq', NULL, '2017-07-16 19:34:17', '2017-07-16 19:34:17');

COMMIT;

